server:
  port: 9191
spring:
  application:
    name: VISOR-MASTER-SERVICE
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver

  datasource:
    url: jdbc:postgresql://localhost:5432/accelerate_dev_migrate
    username: accelerate
    password: password
    
    hikari:
      connection-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 2
      idle-timeout: 30000
      max-lifetime: 120000
      auto-commit: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        type: error


